export default function country(code) {
	switch (code) {
		case 'AF': case 'AFG': return 'Afganistan';
		case 'AX': case 'ALA': return 'Åland Islands';
		case 'AL': case 'ALB': return 'Albania';
		case 'DZ': case 'DZA': return 'Algeria';
		case 'AS': case 'ASM': return 'American Samoa';
		case 'AD': case 'AND': return 'Andorra';
		case 'AO': case 'AGO': return 'Angola';
		case 'AI': case 'AIA': return 'Anguilla';
		case 'AG': case 'ATG': return 'Antigua & Barbuda';
		case 'AR': case 'ARG': return 'Argentina';
		case 'AM': case 'ARM': return 'Armenia';
		case 'AW': case 'ABW': return 'Aruba';
		case 'AU': case 'AUS': return 'Australia';
		case 'AT': case 'AUT': return 'Austria';
		case 'AZ': case 'AZE': return 'Azerbaijan';
		case 'BS': case 'BHS': return 'Bahamas';
		case 'BH': case 'BHR': return 'Bahrain';
		case 'BD': case 'BGD': return 'Bangladesh';
		case 'BB': case 'BRB': return 'Barbados';
		case 'BY': case 'BLR': return 'Belarus';
		case 'BE': case 'BEL': return 'Belgium';
		case 'BZ': case 'BLZ': return 'Belize';
		case 'BJ': case 'BEN': return 'Benin';
		case 'BM': case 'BMU': return 'Bermuda';
		case 'BT': case 'BTN': return 'Bhutan';
		case 'BO': case 'BOL': return 'Bolivia';
		case 'BQ': case 'BES': return 'Bonaire';
		case 'BA': case 'BIH': return 'Bosnia-Herzegovina';
		case 'BW': case 'BWA': return 'Botswana';
		case 'BR': case 'BRA': return 'Brazil';
		case 'IO': case 'IOT': return 'British Indian Ocean Territory';
		case 'VG': case 'VGB': return 'British Virgin Islands';
		case 'BN': case 'BRN': return 'Brunei Darussalam';
		case 'BG': case 'BGR': return 'Bulgaria';
		case 'BF': case 'BFA': return 'Burkina Faso';
		case 'BI': case 'BDI': return 'Burundi';
		case 'KH': case 'KHM': return 'Cambodia';
		case 'CM': case 'CMR': return 'Cameroon';
		case 'CA': case 'CAN': return 'Canada';
		case 'CV': case 'CPV': return 'Cape Verde Islands';
		case 'KY': case 'CYM': return 'Cayman Islands';
		case 'CF': case 'CAF': return 'Central African Republic';
		case 'TD': case 'TCD': return 'Chad';
		case 'CL': case 'CHL': return 'Chile';
		case 'CN': case 'CHN': return 'China';
		case 'CX': case 'CXR': return 'Christmas Island';
		case 'CC': case 'CCK': return 'Cocos (Keeling) Islands';
		case 'CO': case 'COL': return 'Colombia';
		case 'KM': case 'COM': return 'Comoros';
		case 'CG': case 'COG': return 'Congo (Brazzaville)';
		case 'CD': case 'ZAR': return 'Congo (Kinshasa)';
		case 'CK': case 'COK': return 'Cook Islands';
		case 'CR': case 'CRI': return 'Costa Rica';
		case 'HR': case 'HRV': return 'Croatia';
		case 'CU': case 'CUB': return 'Cuba';
		case 'CW': case 'CUW': return 'Curaçao';
		case 'CY': case 'CYP': return 'Cyprus';
		case 'CZ': case 'CZE': return 'Czech Republic';
		case 'DK': case 'DNK': return 'Denmark';
		case 'DJ': case 'DJI': return 'Djibouti';
		case 'DM': case 'DMA': return 'Dominica';
		case 'DO': case 'DOM': return 'Dominican Republic';
		case 'TL': case 'TLS': return 'East Timor';
		case 'EC': case 'ECU': return 'Ecuador';
		case 'EG': case 'EGY': return 'Egypt';
		case 'SV': case 'SLV': return 'El Salvador';
		case 'GQ': case 'GNQ': return 'Equatorial Guinea';
		case 'ER': case 'ERI': return 'Eritrea';
		case 'EE': case 'EST': return 'Estonia';
		case 'ET': case 'ETH': return 'Ethiopia';
		case 'FO': case 'FRO': return 'Faeroe Islands';
		case 'FK': case 'FLK': return 'Falkland Islands';
		case 'FJ': case 'FJI': return 'Fiji';
		case 'FI': case 'FIN': return 'Finland';
		case 'FR': case 'FRA': return 'France';
		case 'GF': case 'GUF': return 'French Guiana';
		case 'PF': case 'PYF': return 'French Polynesia';
		case 'TF': case 'ATF': return 'French Southern Territories';
		case 'GA': case 'GAB': return 'Gabon';
		case 'GM': case 'GMB': return 'Gambia';
		case 'GE': case 'GEO': return 'Georgia';
		case 'DE': case 'DEU': return 'Germany';
		case 'GH': case 'GHA': return 'Ghana';
		case 'GI': case 'GIB': return 'Gibralter';
		case 'GR': case 'GRC': return 'Greece';
		case 'GL': case 'GRL': return 'Greenland';
		case 'GD': case 'GRD': return 'Grenada';
		case 'GP': case 'GLP': return 'Guadeloupe';
		case 'GU': case 'GUM': return 'Guam';
		case 'GT': case 'GTM': return 'Guatemala';
		case 'GG': case 'GGY': return 'Guernsey';
		case 'GN': case 'GIN': return 'Guinea';
		case 'GW': case 'GNB': return 'Guinea-Bissau';
		case 'GY': case 'GUY': return 'Guyana';
		case 'HT': case 'HTI': return 'Haiti';
		case 'VA': case 'VAT': return 'Holy See';
		case 'HN': case 'HND': return 'Honduras';
		case 'HK': case 'HKG': return 'Hong Kong';
		case 'HU': case 'HUN': return 'Hungary';
		case 'IS': case 'ISL': return 'Iceland';
		case 'IN': case 'IND': return 'India';
		case 'ID': case 'IDN': return 'Indonesia';
		case 'IR': case 'IRN': return 'Iran';
		case 'IQ': case 'IRQ': return 'Iraq';
		case 'IE': case 'IRL': return 'Ireland';
		case 'IM': case 'IMN': return 'Isle of Man';
		case 'IL': case 'ISR': return 'Israel';
		case 'IT': case 'ITA': return 'Italy';
		case 'CI': case 'CIV': return 'Ivory Coast';
		case 'JM': case 'JAM': return 'Jamaica';
		case 'JP': case 'JPN': return 'Japan';
		case 'JE': case 'JEY': return 'Jersey';
		case 'JO': case 'JOR': return 'Jordan';
		case 'KZ': case 'KAZ': return 'Kazakhstan';
		case 'KE': case 'KEN': return 'Kenya';
		case 'KI': case 'KIR': return 'Kiribati';
		case 'KW': case 'KWT': return 'Kuwait';
		case 'KG': case 'KGZ': return 'Kyrgyzstan';
		case 'LA': case 'LAO': return 'Laos';
		case 'LV': case 'LVA': return 'Latvia';
		case 'LB': case 'LBN': return 'Lebanon';
		case 'LS': case 'LSO': return 'Lesotho';
		case 'LR': case 'LBR': return 'Liberia';
		case 'LY': case 'LBY': return 'Libya';
		case 'LI': case 'LIE': return 'Liechtenstein';
		case 'LT': case 'LTU': return 'Lithuania';
		case 'LU': case 'LUX': return 'Luxembourg';
		case 'MO': case 'MAC': return 'Macau';
		case 'MK': case 'MKD': return 'Macedonia';
		case 'MG': case 'MDG': return 'Madagascar';
		case 'MW': case 'MWI': return 'Malawi';
		case 'MY': case 'MYS': return 'Malaysia';
		case 'MV': case 'MDV': return 'Maldives';
		case 'ML': case 'MLI': return 'Mali';
		case 'MT': case 'MLT': return 'Malta';
		case 'MH': case 'MHL': return 'Marshall Islands';
		case 'MQ': case 'MTQ': return 'Martinique';
		case 'MR': case 'MRT': return 'Mauritania';
		case 'MU': case 'MUS': return 'Mauritius';
		case 'YT': case 'MYT': return 'Mayotte';
		case 'MX': case 'MEX': return 'Mexico';
		case 'FM': case 'FSM': return 'Micronesia';
		case 'MD': case 'MDA': return 'Moldova';
		case 'MC': case 'MCO': return 'Monaco';
		case 'MN': case 'MNG': return 'Mongolia';
		case 'ME': case 'MNE': return 'Montenegro';
		case 'MS': case 'MSR': return 'Montserrat';
		case 'MA': case 'MAR': return 'Morocco';
		case 'MZ': case 'MOZ': return 'Mozambique';
		case 'MM': case 'MMR': return 'Myanmar';
		case 'NA': case 'NAM': return 'Namibia';
		case 'NR': case 'NRU': return 'Nauru';
		case 'NP': case 'NPL': return 'Nepal';
		case 'AN': case 'ANT': return 'Netherlands Antilles';
		case 'NL': case 'NLD': return 'Netherlands';
		case 'NC': case 'NCL': return 'New Caledonia';
		case 'NZ': case 'NZL': return 'New Zealand';
		case 'NI': case 'NIC': return 'Nicaragua';
		case 'NE': case 'NER': return 'Niger';
		case 'NG': case 'NGA': return 'Nigeria';
		case 'NU': case 'NIU': return 'Niue';
		case 'NF': case 'NFK': return 'Norfolk Island';
		case 'KP': case 'PRK': return 'North Korea';
		case 'MP': case 'MNP': return 'Northern Mariana Islands';
		case 'NO': case 'NOR': return 'Norway';
		case 'OM': case 'OMN': return 'Oman';
		case 'PK': case 'PAK': return 'Pakistan';
		case 'PW': case 'PLW': return 'Palau';
		case 'PS': case 'PSE': return 'Palestinian Territories';
		case 'PA': case 'PAN': return 'Panama';
		case 'PG': case 'PNG': return 'Papua New Guinea';
		case 'PY': case 'PRY': return 'Paraguay';
		case 'PE': case 'PER': return 'Peru';
		case 'PH': case 'PHL': return 'Philippines';
		case 'PN': case 'PCN': return 'Pitcairn Islands';
		case 'PL': case 'POL': return 'Poland';
		case 'PT': case 'PRT': return 'Portugal';
		case 'PR': case 'PRI': return 'Puerto Rico';
		case 'QA': case 'QAT': return 'Qatar';
		case 'RO': case 'ROU': return 'Romania';
		case 'RU': case 'RUS': return 'Russia';
		case 'RW': case 'RWA': return 'Rwanda';
		case 'RE': case 'REU': return 'Réunion';
		case 'BL': case 'BLM': return 'Saint Barthélemy';
		case 'KN': case 'KNA': return 'Saint Christopher & Nevis';
		case 'SH': case 'SHN': return 'Saint Helena';
		case 'LC': case 'LCA': return 'Saint Lucia';
		case 'MF': case 'MAF': return 'Saint Martin';
		case 'PM': case 'SPM': return 'Saint Pierre & Miquelon';
		case 'VC': case 'VCT': return 'Saint Vincent & The Grenadines';
		case 'WS': case 'WSM': return 'Samoa';
		case 'SM': case 'SMR': return 'San Marino';
		case 'ST': case 'STP': return 'Sao Tome & Principe';
		case 'SA': case 'SAU': return 'Saudi Arabia';
		case 'SN': case 'SEN': return 'Senegal';
		case 'RS': case 'SRB': return 'Serbia';
		case 'SC': case 'SYC': return 'Seychelles';
		case 'SL': case 'SLE': return 'Sierra Leone';
		case 'SG': case 'SGP': return 'Singapore';
		case 'SX': case 'SXM': return 'Sint Maarten';
		case 'SK': case 'SVK': return 'Slovakia';
		case 'SI': case 'SVN': return 'Slovenia';
		case 'SB': case 'SLB': return 'Solomon Islands';
		case 'SO': case 'SOM': return 'Somalia';
		case 'ZA': case 'ZAF': return 'South Africa';
		case 'GS': case 'SGS': return 'South Georgia & The South Sandwish Islands';
		case 'KR': case 'KOR': return 'South Korea';
		case 'SS': case 'SSD': return 'South Sudan';
		case 'ES': case 'ESP': return 'Spain';
		case 'LK': case 'LKA': return 'Sri Lanka';
		case 'SD': case 'SDN': return 'Sudan';
		case 'SR': case 'SUR': return 'Suriname';
		case 'SZ': case 'SWZ': return 'Swaziland';
		case 'SE': case 'SWE': return 'Sweden';
		case 'CH': case 'CHE': return 'Switzerland';
		case 'SY': case 'SYR': return 'Syria';
		case 'TW': case 'TWN': return 'Taiwan';
		case 'TJ': case 'TJK': return 'Tajikistan';
		case 'TZ': case 'TZA': return 'Tanzania';
		case 'TH': case 'THA': return 'Thailand';
		case 'TG': case 'TGO': return 'Togo';
		case 'TK': case 'TKL': return 'Tokelau';
		case 'TO': case 'TON': return 'Tonga';
		case 'TT': case 'TTO': return 'Trinidad & Tobago';
		case 'TN': case 'TUN': return 'Tunisia';
		case 'TR': case 'TUR': return 'Turkey';
		case 'TM': case 'TKM': return 'Turkmenistan';
		case 'TC': case 'TCA': return 'Turks & Caicos Islands';
		case 'TV': case 'TUV': return 'Tuvalu';
		case 'UG': case 'UGA': return 'Uganda';
		case 'UA': case 'UKR': return 'Ukraine';
		case 'AE': case 'ARE': return 'United Arab Emirates';
		case 'GB': case 'GBR': return 'United Kingdom';
		case 'US': case 'USA': return 'United States';
		case 'VI': case 'VIR': return 'United States Virgin Islands';
		case 'UY': case 'URY': return 'Uruguay';
		case 'UZ': case 'UZB': return 'Uzbekistan';
		case 'VU': case 'VUT': return 'Vanuatu';
		case 'VE': case 'VEN': return 'Venezuela';
		case 'VN': case 'VNM': return 'Vietnam';
		case 'WF': case 'WLF': return 'Wallis & Futuna';
		case 'EH': case 'ESH': return 'Western Sahara';
		case 'YE': case 'YEM': return 'Yemen';
		case 'ZM': case 'ZMB': return 'Zambia';
		case 'ZW': case 'ZWE': return 'Zimbabwe';
		default: return undefined;
	}
}
